### PR TITLE
Made react ephormal, added sticky message 

### PR DESCRIPTION
**Pull request by DWAA1660**
#2 #46 should be done now

### CODE REVIEW

**Comment by DWAA1660** [comment]
Ready for review!

**Review by DWAA1660 — COMMENTED** [review]
looks good B)

**Review by srnyx — APPROVED** [review]

**Comment by DWAA1660** [comment]
added #9

**Review by srnyx — APPROVED** [review]

**Review by Chrizxz — APPROVED** [review]
*ephemeral

**Pull request merged**
