### PR TITLE
Fixed kick, superban, and unsuperban

### PR DESCRIPTION
**Pull request by DWAA1660**
big changes big fixes epical db stuff

### CODE REVIEW

**Comment by srnyx** [comment]
Fix unsuperban so that all the messages say `unsuperban` instead of `un-superban`/`superunban`

**Comment by DWAA1660** [comment]
I'm gonna add new guilds command so don't accept quite yet

**Comment by DWAA1660** [comment]
Ready for the review! @srnyx @Chrizxz

**Review by srnyx — APPROVED** [review]

**Review by srnyx — APPROVED** [review]

**Comment by DWAA1660** [comment]
#2 i did this now

**Review by srnyx — APPROVED** [review]

**Review by Chrizxz — APPROVED** [review]

**Pull request merged**
